version: 1
anexos:
  "3008": "241"
  "3028":	"474"
  "3029":	"10518"
  "3024":	"11495"
  "3001":	"11497"
  "4801":	"11765"
  "4834":	"12265"
  "4809":	"12502"
  "4805":	"12962"
  "4808":	"14350"
  "3025":	"14791"
  "4812": "15255"
  "4811":	"15382"
  "4810":	"15576"
  "3009":	"15618"
  "3019":	"15630"
  "3021":	"15632"
  "3027":	"15671"
  "4813":	"15691"
  "4838":	"15909"
  "4839":	"16025"
  "3002":	"16026"

nombres:
  "241": "CUYA VALENCIA CARMEN TERESA"
  "474": "IRIARTE OLIVARES OSCAR GUILLERMO"
  "10518": "TORRES SUAREZ GEAN CARLOS"
  "11495": "FRANCO OSIS ROXANA"
  "11497": "QUISPE VELASQUEZ LUCERO"
  "11765": "ABRIL GIRIBALDI MARIA DE JESUS"
  "12265": "CASTILLO ASCA RODRIGO"
  "12502": "CORONEL VALERIO ESTEFANI"
  "12962": "FERNANDEZ FLORES FREIDA"
  "14350": "YUPANQUI OLAECHEA ROCIO ESTHER"
  "14791": "POLICARPO PEÑALOZA DEYLI"
  "15255": "CARMEN CARBAJAL VERONICA"
  "15382": "FLEMING CALLE BRENDA ISABEL"
  "15576": "TOHALINO PAMPAS ALISSON ANNIE"
  "15618": "HUARCAYA VENTURA SHEYLA KIMBERLY"
  "15630": "LOBATON SALAZAR PATRICIA CARMEN"
  "15632": "SANDOVAL CASTILLO EVELYN JUDITH"
  "15671": "GUERRERO PURIZACA YOSELYN YOHANA"
  "15691": "ROMERO TORREJON KAREN LUCERO"
  "15909": "VALDEZ BORJA MARICIELO ISABELA"
  "16025": "MUNGUIA TORRES NATALY ELIZABETH"
  "16026": "GARCIA SANDOVAL EDUARDO"

